/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import com.github.sarxos.webcam.Webcam;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ChupAnh extends javax.swing.JDialog {

    Webcam webcam;
    boolean isRunning = true;

    /**
     * Creates new form ChupAnh
     */
    public ChupAnh(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        webcam = Webcam.getDefault();
        webcam.setViewSize(new Dimension(176, 144));
        webcam.open();
        new videoLoad().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnhChup = new javax.swing.JLabel();
        btnChup = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblAnhChup, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 388, 235));

        btnChup.setBackground(new java.awt.Color(255, 153, 51));
        btnChup.setText("Chụp ảnh");
        btnChup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChupActionPerformed(evt);
            }
        });
        getContentPane().add(btnChup, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 114, 42));

        btnThoat.setBackground(new java.awt.Color(255, 153, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 100, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        webcam.close();
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnChupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChupActionPerformed
        // TODO add your handling code here:
        isRunning = false;
        String tenAnh = JOptionPane.showInputDialog(this, "Nhập tên ảnh .");
        Image image = webcam.getImage();
        try {
            if (image != null) {
                ImageIO.write((RenderedImage) image, "PNG", new File("A:\\Du an 1\\PRO1041-SD18312-Group1_Hung Manh\\logos\\" + tenAnh+".png"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        webcam.close();
    }//GEN-LAST:event_btnChupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChupAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChupAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChupAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChupAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChupAnh dialog = new ChupAnh(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    class videoLoad extends Thread {
        @Override
        public void run() {
            while (isRunning) {
                Image image = webcam.getImage();
                if (image != null) {
                    lblAnhChup.setIcon(new ImageIcon(image));
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChup;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel lblAnhChup;
    // End of variables declaration//GEN-END:variables
}
