/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.HoaDonDAO;
import Entity.HoaDon;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class DanhSachHoaDon extends javax.swing.JPanel {

    HoaDonDAO hddao = new HoaDonDAO();

    /**
     * Creates new form DanhSachHoaDon
     */
    public DanhSachHoaDon() {
        initComponents();
        initTable();
        fillTable();
    }

    private void initTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblDSHD.getModel();
        String[] column = new String[]{
            "Mã HD", "Mã NV", "Mã KH", "Mã PGG", "Ngày tạo", "Số lượng", "Thành tiền", "Trạng thái"
        };
        tableModel.setColumnIdentifiers(column);
    }

    private void fillTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblDSHD.getModel();
        tableModel.setRowCount(0);
        List<HoaDon> list = hddao.danhSachHD();
        System.out.println(list.size()+"");
        for (HoaDon hd : list) {
            tableModel.addRow(new Object[]{
                hd.getMaHoaDon(), hd.getMaNhanVien(), hd.getMaKhachHang(), hd.getMaPhieuGiamGia(), hd.getNgayTaoHoaDon(),hd.getSoLuong(), hd.getThanhToan(),
                hd.getTrangThaiHoaDon()
            });
        }
        tblDSHD.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSHD = new javax.swing.JTable();

        tblDSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDSHD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSHD;
    // End of variables declaration//GEN-END:variables
}
