/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import DAO.LoaiAoDAO;
import Entity.LoaiAo;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class DialogLoaiAo extends javax.swing.JDialog {

    LoaiAoDAO ladao = new LoaiAoDAO();
    int row = -1;

    /**
     * Creates new form FormDanhMuc
     */
    public DialogLoaiAo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initComboBox();
        initTable();
        fillTable();

    }

    private void initTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblLoaiAo.getModel();
        String[] columns = new String[]{
            "Mã Thương hiệu", "Tên thương hiệu", "Trạng thái"
        };

        tableModel.setColumnIdentifiers(columns);
    }

    private void fillTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblLoaiAo.getModel();
        tableModel.setRowCount(0);
        List<LoaiAo> list = ladao.selectAll();
        for (LoaiAo la : list) {
            tableModel.addRow(new Object[]{
                la.getMaLoaiAo(), la.getTenLoaiAo(), la.isTrangThai() ? "Đang hoạt động" : "Ngừng hoạt động"
            });
        }
        tblLoaiAo.setModel(tableModel);
    }

    private void initComboBox() {
        DefaultComboBoxModel boxModel = (DefaultComboBoxModel) cboTrangThai.getModel();
        boxModel.removeAllElements();
        String[] cboItem = new String[]{
            "Đang hoạt động", "Ngừng hoạt động"
        };
        cboTrangThai.setModel(new DefaultComboBoxModel<>(cboItem));
    }

    private LoaiAo getModel() {
        return new LoaiAo(0, txtTenLoaiAo.getText(), cboTrangThai.getSelectedIndex() == 0);
    }

    private boolean validateForm() {
        String tenLoaiAo = txtTenLoaiAo.getText().trim();
        if (tenLoaiAo.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên loại áo không được để trống .");
            return false;
        }
        return true;
    }

    private void clear() {
        txtMaLoaiAo.setText("");
        txtTenLoaiAo.setText("");
        cboTrangThai.setSelectedIndex(0);
        row = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        cboMauSacDS = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        cboSizeDS = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        txtTenLoaiAo = new javax.swing.JTextField();
        txtMaLoaiAo = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiAo = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();

        jLabel30.setText("Màu sắc :");

        cboMauSacDS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMauSacDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMauSacDSActionPerformed(evt);
            }
        });

        jLabel31.setText("Size :");

        cboSizeDS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh mục"));

        jLabel3.setText("Mã loại áo :");

        jLabel1.setText("Tên loại áo :");

        jLabel2.setText("Trạng thái :");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMaLoaiAo.setEnabled(false);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblLoaiAo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoaiAo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiAoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiAo);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLoaiAo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtTenLoaiAo)
                    .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLoaiAo)
                    .addComponent(jLabel3)
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLoaiAo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            if (ladao.KiemTraTenLoaiAo(txtTenLoaiAo.getText())) {
                if (ladao.insert(getModel()) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm loại áo thành công .");
                    fillTable();
                    clear();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm loại áo không thành công .");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tên loại áo đã tồn tại trong bảng .");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (row > -1) {
            if (validateForm()) {
                LoaiAo loaiAo = getModel();
                loaiAo.setMaLoaiAo(Integer.parseInt(txtMaLoaiAo.getText().trim()));
                if (ladao.update(loaiAo) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật loại áo thành công .");
                    fillTable();
                    clear();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật loại áo không thành công . ");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa dòng nào được chọn trên bảng .");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (row > -1) {
            LoaiAo loaiAo = getModel();
            loaiAo.setMaLoaiAo(Integer.parseInt(txtMaLoaiAo.getText().trim()));
            loaiAo.setTrangThai(false);
            if (ladao.update(loaiAo) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa loại áo thành công .");
                fillTable();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa loại áo không thành công . ");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa dòng nào được chọn trên bảng .");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblLoaiAoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiAoMouseClicked
        // TODO add your handling code here:
        row = tblLoaiAo.getSelectedRow();
        txtMaLoaiAo.setText(tblLoaiAo.getValueAt(row, 0).toString());
        txtTenLoaiAo.setText(tblLoaiAo.getValueAt(row, 1).toString());
        if (tblLoaiAo.getValueAt(row, 2).toString().equals("Đang hoạt động")) {
            cboTrangThai.setSelectedIndex(0);
        } else {
            cboTrangThai.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblLoaiAoMouseClicked

    private void cboMauSacDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMauSacDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMauSacDSActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogLoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogLoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogLoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogLoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogLoaiAo dialog = new DialogLoaiAo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMauSacDS;
    private javax.swing.JComboBox<String> cboSizeDS;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoaiAo;
    private javax.swing.JTextField txtMaLoaiAo;
    private javax.swing.JTextField txtTenLoaiAo;
    // End of variables declaration//GEN-END:variables
}
