/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ChatLieuDAO;
import DAO.ChatLieuLoaiAoDAO;
import DAO.LoaiAoDAO;
import Entity.ChatLieu;
import Entity.ChatLieu_LoaiAo;
import Entity.LoaiAo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class DialogChatLieu_LoaiAo extends javax.swing.JDialog {

    ChatLieuLoaiAoDAO clladao = new ChatLieuLoaiAoDAO();
    ChatLieuDAO cldao = new ChatLieuDAO();
    LoaiAoDAO ladao = new LoaiAoDAO();
    int row = -1;

    /**
     * Creates new form FormChatLieu_LoaiAo
     */
    public DialogChatLieu_LoaiAo() {
        initComponents();
        initTable();
        initComboboxLoaiAo();
        cboLoaiAo.setSelectedIndex(0);
        initComboboxChatLieu();
        cboChatLieu.setSelectedIndex(0);
        initComboboxTrangThai();
        fillTable();
    }

    private void initTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblChatLieuLoaiAo.getModel();
        String[] columns = new String[]{
            "Mã chất liệu loại áo", "Tên chất liệu", "Tên loại áo", "Trạng thái"
        };
        tableModel.setColumnIdentifiers(columns);

    }

    private void fillTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblChatLieuLoaiAo.getModel();
        tableModel.setRowCount(0);
        List<ChatLieu_LoaiAo> list = clladao.selectAll();
        for (ChatLieu_LoaiAo clla : list) {
            tableModel.addRow(new Object[]{
                clla.getMaChatLieuLoaiAo(), cldao.selectById(clla.getMaChatLieu()), ladao.selectById(clla.getMaLoaiAo()), clla.isTrangThai() ? "Đang hoạt động" : "Ngừng hoạt động"
            });
        }
        tblChatLieuLoaiAo.setModel(tableModel);
    }

    private void initComboboxChatLieu() {
        DefaultComboBoxModel boxModel = (DefaultComboBoxModel) cboChatLieu.getModel();
        boxModel.removeAllElements();
        List<ChatLieu> list = cldao.selectAll();
        for (ChatLieu cl : list) {
            boxModel.addElement(cl);
        }

        cboChatLieu.setModel(boxModel);
    }

    private void initComboboxLoaiAo() {
        DefaultComboBoxModel boxModel = (DefaultComboBoxModel) cboLoaiAo.getModel();
        boxModel.removeAllElements();
        List<LoaiAo> list = ladao.selectAll();
        for (LoaiAo la : list) {
            boxModel.addElement(la);
        }
        cboLoaiAo.setModel(boxModel);
    }

    private void initComboboxTrangThai() {
        DefaultComboBoxModel boxModel = (DefaultComboBoxModel) cboTrangThai.getModel();
        boxModel.removeAllElements();
        String[] cboList = new String[]{
            "Đang hoạt động", "Ngừng họat động"
        };
        for (String tt : cboList) {
            boxModel.addElement(tt);
        }
        cboTrangThai.setModel(boxModel);
    }

    private ChatLieu_LoaiAo getModel() {
        LoaiAo la = (LoaiAo) cboLoaiAo.getSelectedItem();
        ChatLieu cl = (ChatLieu) cboChatLieu.getSelectedItem();
        return new ChatLieu_LoaiAo(0, la.getMaLoaiAo(), cl.getMaChatLieu(), cboTrangThai.getSelectedItem() == "Đang hoạt động" ? true : false);
    }

    private void clear() {
        txtMaCLLA.setText("");
        cboChatLieu.setSelectedIndex(0);
        cboLoaiAo.setSelectedIndex(0);
        cboTrangThai.setSelectedIndex(0);
        row = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChatLieuLoaiAo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cboChatLieu = new javax.swing.JComboBox<>();
        btnThemLoaiAo = new javax.swing.JButton();
        cboLoaiAo = new javax.swing.JComboBox<>();
        txtMaCLLA = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        btnThemChatLieu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chất liệu và  loại áo"));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblChatLieuLoaiAo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChatLieuLoaiAo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChatLieuLoaiAoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChatLieuLoaiAo);

        cboChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemLoaiAo.setText("+");
        btnThemLoaiAo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiAoActionPerformed(evt);
            }
        });

        cboLoaiAo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMaCLLA.setEnabled(false);

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemChatLieu.setText("+");
        btnThemChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChatLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaCLLA)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboLoaiAo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemLoaiAo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaCLLA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemChatLieu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLoaiAo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemLoaiAo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setText("Mã CL_LA :");
        jPanel3.add(jLabel1);

        jLabel4.setText("Tên chất liệu :");
        jPanel3.add(jLabel4);

        jLabel2.setText("Tên loại áo :");
        jPanel3.add(jLabel2);

        jLabel3.setText("Trạng thái :");
        jPanel3.add(jLabel3);

        jButton1.setText("Clear");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ChatLieu cl = (ChatLieu) cboChatLieu.getSelectedItem();
        LoaiAo la = (LoaiAo) cboLoaiAo.getSelectedItem();
        if (clladao.getChatLieuLoaiAo(cl.getMaChatLieu(), la.getMaLoaiAo()) == null) {
            if (clladao.insert(getModel()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm mới chất liệu loại áo thành công .");
                fillTable();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm mới chất liệu loại áo không thành công .");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chất liệu của loại áo đã có trong cơ sở dữ liệu .");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:

        if (row > -1) {
            ChatLieu_LoaiAo chatLieu_LoaiAo = getModel();
            System.out.println(chatLieu_LoaiAo.isTrangThai());
            System.out.println(chatLieu_LoaiAo.getMaChatLieu());
            System.out.println(chatLieu_LoaiAo.getMaLoaiAo());
            chatLieu_LoaiAo.setMaChatLieuLoaiAo(Integer.parseInt(txtMaCLLA.getText().trim()));
            System.out.println(chatLieu_LoaiAo.getMaChatLieuLoaiAo());
            if (clladao.update(chatLieu_LoaiAo) > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật chất liệu loại áo thành công .");
                fillTable();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật chất liệu loại áo không thành công .");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa dòng nào trên bảng được chọn .");
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (row > -1) {
            ChatLieu_LoaiAo clla = getModel();
            clla.setMaChatLieuLoaiAo(Integer.parseInt(txtMaCLLA.getText().trim()));
            clla.setTrangThai(false);
            System.out.println(clla.getMaChatLieu());
            System.out.println(clla.getMaLoaiAo());
            if (clladao.update(clla) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa chất liệu loại áo thành công .");
                fillTable();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa chất liệu loại áo không thành công .");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa dòng nào trên bảng được chọn .");
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblChatLieuLoaiAoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChatLieuLoaiAoMouseClicked
        // TODO add your handling code here:
        row = tblChatLieuLoaiAo.getSelectedRow();
        txtMaCLLA.setText(tblChatLieuLoaiAo.getValueAt(row, 0).toString());
        Object selectedCl = tblChatLieuLoaiAo.getValueAt(row, 1);
        DefaultComboBoxModel<ChatLieu> cbBoxModel1 = (DefaultComboBoxModel) cboChatLieu.getModel();
        for (int i = 0; i < cbBoxModel1.getSize(); i++) {
            ChatLieu chatlieu = cbBoxModel1.getElementAt(i);
            if (chatlieu.toString().equals(selectedCl.toString())) {
                cboChatLieu.setSelectedItem(chatlieu);
            }
        }
        Object selectedLa = tblChatLieuLoaiAo.getValueAt(row, 2);
        DefaultComboBoxModel<LoaiAo> cbBoxModel2 = (DefaultComboBoxModel) cboLoaiAo.getModel();
        for (int i = 0; i < cbBoxModel2.getSize(); i++) {
            LoaiAo loaiAo = cbBoxModel2.getElementAt(i);
            if (loaiAo.toString().equals(selectedCl.toString())) {
                cboLoaiAo.setSelectedItem(loaiAo);
            }
        }
        if (tblChatLieuLoaiAo.getValueAt(row, 3).toString().equals("Đang hoạt động")) {
            cboTrangThai.setSelectedIndex(0);
        } else {
            cboTrangThai.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblChatLieuLoaiAoMouseClicked

    private void btnThemChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChatLieuActionPerformed
        // TODO add your handling code here:
        DialogChatLieu fcl = new DialogChatLieu(null, true);
        fcl.setVisible(true);
        initComboboxLoaiAo();
        initComboboxChatLieu();
    }//GEN-LAST:event_btnThemChatLieuActionPerformed

    private void btnThemLoaiAoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiAoActionPerformed
        // TODO add your handling code here:
        DialogLoaiAo fla = new DialogLoaiAo(null, true);
        fla.setVisible(true);
        initComboboxLoaiAo();
        initComboboxChatLieu();

    }//GEN-LAST:event_btnThemLoaiAoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogChatLieu_LoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogChatLieu_LoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogChatLieu_LoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogChatLieu_LoaiAo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogChatLieu_LoaiAo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemChatLieu;
    private javax.swing.JButton btnThemLoaiAo;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboChatLieu;
    private javax.swing.JComboBox<String> cboLoaiAo;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChatLieuLoaiAo;
    private javax.swing.JTextField txtMaCLLA;
    // End of variables declaration//GEN-END:variables
}
